project: ecalls_ar_sentiment_mvp
paths:
  raw: "data/raw/Earnings Call Transcripts – NASDAQ (2016-2020)/Transcripts"
  interim: data/interim
  processed: data/processed
  reports: reports
finbert:
  model_name: ProsusAI/finbert
  max_tokens: 256
  stride: 64
event_study:
  market: ^GSPC
  window: [-3, 3]
